# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'data source', 'verbose_name_plural': 'data sources'},
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together=set([('owner', 'file_path')]),
        ),
    ]
