# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:09
from __future__ import unicode_literals

import data_sources.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_auto_20160505_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'text'), ('FASTA', 'FASTA'), ('FASTQ', 'FASTQ'), ('BINARY', 'binary')], max_length=32, verbose_name='file type'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sample_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='sample name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='checksum',
            field=data_sources.fields.SHA256ChecksumField(blank=True, help_text='Hexadecimal checksum generated by SHA256 hash algorithm.', verbose_name='SHA256 checksum'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='file_path',
            field=models.CharField(help_text="Relative path under user's data source directory.", max_length=1023, verbose_name='file path'),
        ),
    ]
