# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_auto_20160527_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('FASTA', 'FASTA'), ('FASTQ', 'FASTQ'), ('BINARY', 'Binary')], max_length=32, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
    ]
