# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0004_auto_20160607_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('sample_name', 'file_path'), 'verbose_name': 'data source', 'verbose_name_plural': 'data sources'},
        ),
    ]
