# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the access link is publicly visible.', verbose_name='is public'),
        ),
    ]
