# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0002_auto_20160616_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiments', '0003_auto_20160614_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNASeqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description about this analysis. Can be written in <a href="http://commonmark.org/">Markdown</a> markup language.', verbose_name='description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_finished', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='date finished')),
                ('execution_status', models.CharField(choices=[('INIT', 'Initiating'), ('QUEUEING', 'Waiting in the queue'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='INIT', editable=False, max_length=63)),
                ('quality_check', models.BooleanField(default=True, help_text='Generate a quality check report based on FastQC')),
                ('trim_adapter', models.BooleanField(default=False, help_text="Trim illumina 3' adapter. <strong>Currently no support for this option.</strong>")),
                ('rm_duplicate', models.BooleanField(default=False, help_text='Remove PCR duplication based on the genome alignment of reads during sequencing using <a href="http://broadinstitute.github.io/picard/">Picard</a>. <strong>Currently no support for this option.</strong>', verbose_name='Remove PCR duplication')),
                ('genome_aligner', models.CharField(choices=[('Tophat_2.1.1', 'Tophat v2.1.1'), ('STAR_2.5.0', 'STAR v2.5.0')], max_length=128)),
                ('tophat_max_multihits', models.PositiveIntegerField(blank=True, default=20, help_text='Instructs TopHat to allow up to this many alignments to the reference for a given read, and choose the alignments based on their alignment scores if there are more than this number. The default is 20 for read mapping. If there are more alignments with the same score than this number, TopHat will randomly report only this many alignments.', verbose_name='Max multi-hits')),
                ('tophat_library_type', models.CharField(blank=True, choices=[('FR-UNSTRANDED', 'Unstranded (Ex. Standard illumnia)'), ('FR-FIRSTSTRAND', 'First-stranded (Ex. Stranded specific sequcing, dUTP, NSR, NNSR)'), ('FR-SECONDSTRAND', 'Second-stranded (Ex. Standard SOLiD)')], default='FR-UNSTRANDED', help_text='Consider supplying library type options below to select the correct RNA-seq protocol. The default is unstranded.', max_length=16, verbose_name='Library type')),
                ('star_separate_unmapped_reads', models.BooleanField(default=False, help_text='Put unmapped or partially mapped (one of the paired reads is mapped) in a separate FASTA/Q file.', verbose_name='separate unmapped reads')),
                ('experiment', models.ForeignKey(help_text='Previously defined experiment, which contains how sources are grouped as samples and conditions.', on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='experiments.Experiment')),
                ('genome_reference', models.ForeignKey(help_text='The genome reference in use.', on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='analyses.GenomeReference')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'get_latest_by': ('date_finished', 'date_created'),
                'abstract': False,
            },
        ),
    ]
