# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_report'),
        ('rna_seq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnaseqmodel',
            options={'verbose_name': 'RNA-Seq analysis', 'verbose_name_plural': 'RNA-Seq analyses'},
        ),
        migrations.AddField(
            model_name='rnaseqmodel',
            name='report',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyses.Report'),
        ),
    ]
