# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 09:52
from __future__ import unicode_literals

import analyses.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_auto_20160702_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNASeqExeDetail',
            fields=[
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='execution_detail', serialize=False, to='rna_seq.RNASeqModel')),
                ('stage_qc', analyses.fields.StageStatusField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('SKIPED', 'Skiped')], default='WAITING', max_length=32)),
                ('stage_alignment', analyses.fields.StageStatusField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('SKIPED', 'Skiped')], default='WAITING', max_length=32)),
                ('stage_cufflinks', analyses.fields.StageStatusField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('SKIPED', 'Skiped')], default='WAITING', max_length=32)),
                ('stage_cuffdiff', analyses.fields.StageStatusField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('SKIPED', 'Skiped')], default='WAITING', max_length=32)),
            ],
        ),
    ]
