# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0003_rnaseqexedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnaseqexedetail',
            options={'verbose_name': 'RNA-Seq detail', 'verbose_name_plural': 'RNA-Seq detail'},
        ),
    ]
