import logging
from pathlib import Path
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.utils import ValueDescriptionChoiceEnum
from .fields import SHA256ChecksumField


class FileType(ValueDescriptionChoiceEnum):
    TEXT = (_('Text'), _('File containing plain text'))
    FASTA = (_('FASTA'), _('FASTA file'))
    FASTQ = (_('FASTQ'), _('FASTQ file'))
    BINARY = (_('Binary'), _('Binary file that cannot be readable by human'))


class DataSource(models.Model):
    """A model to store user's data sources.

    """
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='data_sources',
    )

    # Don't use FilePathField, not that useful.
    # Only check file existence at forms
    file_path = models.CharField(
        max_length=1023,
        verbose_name=_("file path"),
        help_text=_("Relative path under user's data source directory."),
    )
    checksum = SHA256ChecksumField(
        blank=True,
        verbose_name=_("SHA256 checksum"),
        help_text=_(
            "Hexadecimal checksum generated by SHA256 hash algorithm."
        ),
    )
    sample_name = models.CharField(
        max_length=512,
        blank=True,
        verbose_name=_("sample name"),
    )
    file_type = models.CharField(
        choices=FileType.choices(),
        max_length=32,
        blank=True,
        verbose_name=_("file type"),
    )
    metadata = JSONField(
        blank=True,
        default=dict,
        verbose_name=_("metadata")
    )

    class Meta:
        verbose_name = _('data source')
        verbose_name_plural = _('data sources')
        unique_together = ('owner', 'file_path')
        ordering = ('sample_name', 'file_path')

    def __str__(self):
        return (
            '%s (owner: %s)' %
            (self.get_rel_file_path(), self.owner.name)
        )

    def get_absolute_url(self):
        return reverse('update_data_source', kwargs={'pk': self.pk})

    def get_rel_file_path(self):
        return Path(str(self.owner.pk), self.file_path)

    def get_full_file_path(self):
        full_file_path = settings.BIOCLOUD_DATA_SOURCES_DIR.joinpath(
            str(self.owner.pk), self.file_path
        )
        return full_file_path

    @property
    def rel_file_path(self):
        return self.get_rel_file_path()

    @property
    def full_file_path(self):
        return self.get_full_file_path()
